# Generated by Django 5.0.6 on 2024-07-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.CharField(max_length=200, verbose_name="slug"),
        ),
    ]
