# Generated by Django 4.2 on 2024-07-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": [
                    "name_product",
                    "category",
                    "price",
                    "created_at",
                    "updated_at",
                ],
                "permissions": [
                    ("can_edit_is_published", "Can edit is published"),
                    ("can_edit_description", "Can edit description"),
                    ("can_edit_category", "Can edit category"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Опубликовать продукт",
                verbose_name="Опубликовано",
            ),
        ),
    ]
